---
title: " thedatasavvycorner.com Privacy Policy"
date: 01 February 2024
---

Your data protection rights
Under data protection law, you have rights including:
Your right of access - You have the right to ask us for copies of your personal information. 
Your right to rectification - You have the right to ask us to rectify personal information you think is inaccurate. You also have the right to ask us to complete information you think is incomplete. 
Your right to erasure - You have the right to ask us to erase your personal information in certain circumstances. 
Your right to restriction of processing - You have the right to ask us to restrict the processing of your personal information in certain circumstances. 
Your right to object to processing - You have the the right to object to the processing of your personal information in certain circumstances.
Your right to data portability - You have the right to ask that we transfer the personal information you gave us to another organisation, or to you, in certain circumstances.
You are not required to pay any charge for exercising your rights. If you make a request, we have one month to respond to you.

How to complain

You can complain to the ICO if you are unhappy with how we have used your data.
The ICO’s address:            
Information Commissioner’s Office
Wycliffe House
Water Lane
Wilmslow
Cheshire
SK9 5AF

Helpline number: 0303 123 1113
ICO website: https://www.ico.org.uk
Tell people how to make a complaint to you here. Include the ICO’s address.
 
